# Generated by Django 6.0.5 on 2026-05-21 20:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notif_type', models.CharField(choices=[('low_stock', 'Stock faible'), ('out_of_stock', 'Rupture de stock'), ('product_created', 'Nouveau produit'), ('product_updated', 'Produit mis à jour'), ('product_deleted', 'Produit supprimé'), ('product_review', 'Nouvelle évaluation'), ('new_order', 'Nouvelle commande'), ('order_confirmed', 'Commande confirmée'), ('order_shipped', 'Commande expédiée'), ('order_delivered', 'Commande livrée'), ('order_cancelled', 'Commande annulée'), ('payment_success', 'Paiement réussi'), ('payment_failed', 'Paiement échoué'), ('payment_pending', 'Paiement en attente'), ('subscription_expiring', 'Abonnement bientôt expiré'), ('subscription_expired', 'Abonnement expiré'), ('subscription_renewed', 'Abonnement renouvelé'), ('pub_success', 'Publication réussie'), ('pub_failed', 'Publication échouée'), ('ai_done', 'Génération IA terminée'), ('ai_failed', 'Génération IA échouée'), ('ai_progress', 'Génération IA en cours'), ('system', 'Notification système')], max_length=30)),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Succès'), ('warning', 'Avertissement'), ('error', 'Erreur')], default='info', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
