# Generated by Django 6.0.5 on 2026-05-21 20:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('business', 'Business')], unique=True)),
                ('interval', models.CharField(choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel')], default='monthly', max_length=10)),
                ('price_africa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_global', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('max_flyers_ai', models.PositiveIntegerField(blank=True, null=True)),
                ('max_video_ai', models.PositiveIntegerField(blank=True, null=True)),
                ('max_text_ai', models.PositiveIntegerField(blank=True, null=True)),
                ('max_ai_requests', models.PositiveIntegerField(blank=True, null=True)),
                ('max_products', models.PositiveIntegerField(default=10)),
                ('max_orders', models.PositiveIntegerField(blank=True, null=True)),
                ('has_sira_bot', models.BooleanField(default=False)),
                ('sira_auto_reply', models.BooleanField(default=False)),
                ('sira_order_capture', models.BooleanField(default=False)),
                ('sira_location_fetch', models.BooleanField(default=False)),
                ('has_studio', models.BooleanField(default=True)),
                ('has_bg_removal', models.BooleanField(default=False)),
                ('has_auto_publish', models.BooleanField(default=False)),
                ('has_smart_schedule', models.BooleanField(default=False)),
                ('has_analytics', models.BooleanField(default=False)),
                ('has_market_analysis', models.BooleanField(default=False)),
                ('has_whatsapp_notif', models.BooleanField(default=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100)),
                ('stripe_product_id', models.CharField(blank=True, max_length=100)),
                ('geniuspay_plan_id', models.CharField(blank=True, max_length=100)),
                ('cinetpay_plan_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['price_global'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('cinetpay', 'CinetPay'), ('geniuspay', 'GeniusPay')], max_length=20)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log webhook',
                'verbose_name_plural': 'Logs webhooks',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué'), ('refunded', 'Remboursé'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('cinetpay', 'CinetPay'), ('geniuspay', 'GeniusPay'), ('manual', 'Manuel')], max_length=20)),
                ('provider_tx_id', models.CharField(blank=True, max_length=255)),
                ('provider_checkout_id', models.CharField(blank=True, max_length=255)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.plan')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50, unique=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='billing.payment')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trial', 'Essai'), ('active', 'Actif'), ('past_due', 'Paiement en retard'), ('cancelled', 'Annulé'), ('expired', 'Expiré')], default='trial', max_length=20)),
                ('provider', models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('cinetpay', 'CinetPay'), ('geniuspay', 'GeniusPay'), ('manual', 'Manuel (admin)')], max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('provider_customer_id', models.CharField(blank=True, max_length=100)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.subscription'),
        ),
    ]
