# Generated by Django 6.0.5 on 2026-05-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_plan_max_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='max_products',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
