# Generated by Django 6.0.5 on 2026-05-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_plan_max_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google_pay', 'Google Pay'), ('stripe', 'Stripe'), ('cinetpay', 'CinetPay'), ('geniuspay', 'GeniusPay')], max_length=20, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Config passerelle',
                'verbose_name_plural': 'Configs passerelles',
            },
        ),
        migrations.RunPython(
            # google_pay actif par défaut — les autres désactivés jusqu'à ajout des clés
            lambda apps, schema_editor: apps.get_model('billing', 'GatewayConfig').objects.bulk_create([
                apps.get_model('billing', 'GatewayConfig')(provider='google_pay', is_enabled=True),
                apps.get_model('billing', 'GatewayConfig')(provider='stripe',     is_enabled=False),
                apps.get_model('billing', 'GatewayConfig')(provider='cinetpay',   is_enabled=False),
                apps.get_model('billing', 'GatewayConfig')(provider='geniuspay',  is_enabled=False),
            ]),
            migrations.RunPython.noop,
        ),
    ]
