web: gunicorn AfriSell.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 120
worker: celery -A AfriSell worker --loglevel=info --concurrency=2
beat: celery -A AfriSell beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
