# Generated by Django 6.0.5 on 2026-05-21 20:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('direct', 'Lien direct'), ('other', 'Autre')], default='direct', max_length=20)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='catalogue.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to='accounts.shop')),
            ],
            options={
                'verbose_name': 'Vue produit',
                'verbose_name_plural': 'Vues produits',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('confirmed_orders', models.PositiveIntegerField(default=0)),
                ('delivered_orders', models.PositiveIntegerField(default=0)),
                ('cancelled_orders', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unique_customers', models.PositiveIntegerField(default=0)),
                ('product_views', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='accounts.shop')),
            ],
            options={
                'verbose_name': 'Stat quotidienne',
                'verbose_name_plural': 'Stats quotidiennes',
                'ordering': ['-date'],
                'unique_together': {('shop', 'date')},
            },
        ),
    ]
