# Generated by Django 6.0.5 on 2026-05-21 20:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartScheduleSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=20)),
                ('suggested_slots', models.JSONField(default=list)),
                ('analysis', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suggestion horaire',
                'verbose_name_plural': 'Suggestions horaires',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudioAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('flyer', 'Flyer publicitaire'), ('image', 'Image produit améliorée'), ('text', 'Texte publicitaire'), ('video', 'Vidéo produit'), ('montage', 'Montage vidéo')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En génération'), ('done', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('source_image', models.ImageField(blank=True, null=True, upload_to='studio/sources/')),
                ('generated_file', models.FileField(blank=True, null=True, upload_to='studio/generated/')),
                ('generated_url', models.URLField(blank=True)),
                ('generated_text', models.TextField(blank=True)),
                ('prompt_used', models.TextField(blank=True)),
                ('ai_model_used', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studio_assets', to='catalogue.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Studio',
                'verbose_name_plural': 'Assets Studio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicationPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp Status')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Programmé'), ('published', 'Publié'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='draft', max_length=20)),
                ('caption', models.TextField(blank=True)),
                ('hashtags', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('platform_post_id', models.CharField(blank=True, max_length=255)),
                ('platform_url', models.URLField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_posts', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='studio.studioasset')),
            ],
            options={
                'verbose_name': 'Post publication',
                'verbose_name_plural': 'Posts publication',
                'ordering': ['-created_at'],
            },
        ),
    ]
