# Generated by Django 6.0.5 on 2026-05-21 20:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('rupture', 'Rupture de stock'), ('bientot', 'Disponible bientôt')], default='active', max_length=20)),
                ('category', models.CharField(choices=[('alimentation', 'Alimentation'), ('electronique', 'Électronique'), ('vetements', 'Vêtements'), ('beaute', 'Beauté & Cosmétiques'), ('maison', 'Maison & Décoration'), ('sante', 'Santé & Bien-être'), ('sport', 'Sport & Loisirs'), ('informatique', 'Informatique'), ('telephonie', 'Téléphonie'), ('automobile', 'Automobile'), ('agriculture', 'Agriculture'), ('services', 'Services'), ('autre', 'Autre')], max_length=50)),
                ('custom_category', models.CharField(blank=True, max_length=100)),
                ('published_whatsapp', models.BooleanField(default=False)),
                ('published_facebook', models.BooleanField(default=False)),
                ('published_instagram', models.BooleanField(default=False)),
                ('published_tiktok', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(limit_choices_to={'role': 'tenant'}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
    ]
