# Generated by Django 6.0.5 on 2026-05-21 20:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalogue', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiraConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('twilio_number', models.CharField(blank=True, max_length=20)),
                ('greeting_message', models.TextField(default="Bonjour 👋 Je suis SIRA, l'assistant de {shop_name} !\nTapez *catalogue* pour voir nos produits ou choisissez directement 👇")),
                ('catalogue_intro', models.TextField(default='Voici nos produits disponibles 🛍️ :\n\n{product_list}\n\nTapez le *numéro* ou le *nom* du produit que vous souhaitez commander.')),
                ('order_confirmation_message', models.TextField(default='✅ Votre commande a bien été reçue !\n\n📦 *{product_name}* × {quantity}\n💰 Total : {total} XOF\n🔖 Réf : {reference}\n\nLe vendeur vous contactera très vite pour la livraison.')),
                ('out_of_hours_message', models.TextField(default="Bonjour 👋 Nous sommes actuellement fermés. Nous répondrons dès l'ouverture. Merci de votre patience !")),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('dioula', 'Dioula'), ('wolof', 'Wolof')], default='fr', max_length=10)),
                ('working_hours_start', models.TimeField(blank=True, null=True)),
                ('working_hours_end', models.TimeField(blank=True, null=True)),
                ('auto_confirm_orders', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sira_config', to='accounts.shop')),
            ],
            options={
                'verbose_name': 'Config SIRA',
                'verbose_name_plural': 'Configs SIRA',
            },
        ),
        migrations.CreateModel(
            name='SiraConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_phone', models.CharField(max_length=30)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(choices=[('idle', 'En attente'), ('browsing', 'Navigation catalogue'), ('selecting', 'Sélection produit'), ('confirming', 'Confirmation commande'), ('awaiting_location', 'Attente localisation'), ('completed', 'Commande créée'), ('cancelled', 'Annulé')], default='idle', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('client_note', models.TextField(blank=True)),
                ('client_latitude', models.FloatField(blank=True, null=True)),
                ('client_longitude', models.FloatField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sira_conversation', to='orders.order')),
                ('selected_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sira_conversations', to='catalogue.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sira_conversations', to='accounts.shop')),
            ],
            options={
                'verbose_name': 'Conversation SIRA',
                'verbose_name_plural': 'Conversations SIRA',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='SiraMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('inbound', 'Reçu du client'), ('outbound', 'Envoyé par SIRA')], max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Texte'), ('audio', 'Audio / Vocal'), ('location', 'Position GPS'), ('image', 'Image'), ('system', 'Système')], default='text', max_length=10)),
                ('body', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True)),
                ('transcription', models.TextField(blank=True)),
                ('intent', models.CharField(blank=True, max_length=50)),
                ('raw_payload', models.JSONField(default=dict)),
                ('twilio_sid', models.CharField(blank=True, max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sira.siraconversation')),
            ],
            options={
                'verbose_name': 'Message SIRA',
                'verbose_name_plural': 'Messages SIRA',
                'ordering': ['sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='siraconversation',
            index=models.Index(fields=['shop', 'client_phone', 'state'], name='sira_siraco_shop_id_ffe581_idx'),
        ),
    ]
