# Generated by Django 6.0.5 on 2026-05-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sira', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siraconfig',
            name='wa_provider',
            field=models.CharField(choices=[('twilio', 'Twilio'), ('bridge', 'WA-Bridge (QR)'), ('meta', 'Meta Cloud API')], default='twilio', max_length=10),
        ),
    ]
