# Generated by Django 6.0.5 on 2026-05-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sira', '0002_siraconfig_wa_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='siraconfig',
            name='meta_phone_number_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
