# Generated by Django 6.0.5 on 2026-05-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sira', '0003_siraconfig_meta_phone_number_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='siraconfig',
            name='bot_name',
            field=models.CharField(default='SIRA', max_length=50),
        ),
    ]
